title: Titan Demo Group
description: Residential demolition made easy for homeowners
url: "https://titandemogroup.com"
baseurl: ""

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
