
title: Titan Demo Group
email: fmoreno@titandemogroup.com
description: >-
  Residential demolition experts serving Henderson and the Las Vegas Valley.
baseurl: ""
url: "https://titandemogroup.com"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

paginate: 5
paginate_path: /page:num/
markdown: kramdown
highlighter: rouge
